proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

grpc_options:

  port: 9000

  grpc_servicer_functions: []

logging_config:

  encoding: TEXT

  log_level: INFO

  logs_dir: null

  enable_access_log: true

applications:

- name: ImageGeneratorApp
  route_prefix: /generate_image
  import_path: serve:app
  runtime_env:
    working_dir: "https://storage.cloud.google.com/eternal-ai/JamesNBC/maxmulti.zip"
    pip:  
      - diffusers[torch]
      - peft
    working_dir: 
  deployments:
  - name: RayImageGenerator
    num_replicas: 4
    ray_actor_options:
      num_cpus: 0.25
      num_gpus: 0.25
