proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

grpc_options:

  port: 9000

  grpc_servicer_functions: []

logging_config:

  encoding: TEXT

  log_level: INFO

  logs_dir: null

  enable_access_log: true

applications:

- name: ImageGeneratorApp
  route_prefix: /generate_image
  import_path: serve:image_generator_app
  runtime_env:
    working_dir: "https://github.com/James-NBC/NewSDInference.git"
    pip:  
      - ray[serve]
      - diffusers[torch]
      - peft
    working_dir: 
  deployments:
  - name: RayImageGenerator
    num_replicas: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 1.0
